### ISSUE TITLE
Plumble doesn't reconnect after lost connection

### ISSUE THREAD

**Issue by mivade** [Morlunk/Plumble#77]
In the running app thing (I don't know what it's called.... the thing that shows details on all the status icons on the top left), Plumble says it will attempt to reconnect in 10 seconds after losing the connection to the server. However, this never seems to happen and instead you have to manually reconnect.

This is version 3.2.0.

**Comment by hansharhoff** [comment]
Does reconnect ever work for someone? Or is it a specific bug for certain phones? Can anyone confirm that reconnect has worked for them?

**Comment by BuddyButterfly** [comment]
Hi hansharhoff,

I definitely can confirm this behaviour. I am testing Plumble in a professional environment and this is one of the highest prio obstacles. The connection management definitely need overhaul. I did not find the time to taggle this but this is what I wanted to contribute to as the next action.  I already had email conversation about this with Andrew. The requirements would be (from my side. Just a draft, open for discussion).

R1)
Always stay online in background if possible, reconnecting as fast as possible in background.
Do not interrupt GUI with dialogs when state transitions happen.

R2)
Connection and disconnection shall not be done with some pinging or other regular tasks. Instead it should directly be linked to the Network States that Android gives. So, the transitions in the state machine of Android should trigger the transitions in Plumble.  With this, Plumble does not have to do any task but directly react on network being available or not.

R3)
Online status should be shown in a small status button that reflects the connection state:
"On" in green, "Off" in red, "Connecting/Disconnecting" in yellow. This is just a proposal. Wordings or coloring can be changed. Gott position would be beside the server name.

R4) (<<optional>> or <<later>>)
The user could be warned with a dialog, if he wants to do stuff that needs connection when Plumble is offline. Though, Settings and other stuff could be touchable.

This is the first draft for the reqs from my side. I am looking forward in receiving your feedback. Lets hack together the reqs how people would like to have it and then move on implementing it.

Cheers,
Matt

**Comment by Morlunk** [comment]
@BuddyButterfly, I agree that responding to Android connectivity broadcasts would be a useful solution to improving reconnect stability. Your suggestions in general sound good.

I'm going to do some work on revamping the reconnection logic (right now I agree that it's quite ugly); thank you all for your patience. It appears that the current implementation works for only a small subset of possible disconnection causes.

**Comment by BuddyButterfly** [comment]
@Morlunk, no need for thanking for patience ;-) We thank you for providing such a cool app!

**Comment by BuddyButterfly** [comment]
@Morlunk, I see, you did change reconnection behaviour. Though, there is still a dialog comming into users way and a delay of 10s. I just tested your changes. When disabling network access totally (no mobile data and now wifi), the dialog keeps displaying and a reconnection try is done every 10s. There should be no change until the network changes. If it changes, then it should reconnect immediately. Cause this would mean that there is no connection for 10s if there was an intermittant connection loss (which happens quite often when traveling with the mobile).

**Comment by Morlunk** [comment]
@BuddyButterfly you're correct in that the current set of reconnect changes are not yet complete. I committed roughly half of the reconnection logic overhaul for nightly testing.

**Comment by Morlunk** [comment]
With the new reconnection logic, this bug should be fixed. If there is no connectivity at the time of disconnect, we wait until connectivity is restored before attempting reconnection.

**Comment by BuddyButterfly** [comment]
There are still some issues with the latest version.
    
    I am not able to connect to my own server, which does not have the
    default port.
    It gis immediate connection error. And then tries to reconnect every
    10s flooding
    me with vibration and dialog.
    
    The latest version also does not work with respect to PTT. When I
    press PTT it crashes
    immediately.
    
    
    Am 19.01.2015 um 23:37 schrieb Andrew Comminos:
    >
      > With the new reconnection logic, this bug should be fixed. If
      there is no connectivity at the time of disconnect, we wait until
      connectivity is restored before attempting reconnection.
      >
      > —
      > Reply to this email directly or view it on GitHub
<https://github.com/Morlunk/Plumble/issues/77#issuecomment-70573778>.
      >
