### ISSUE TITLE
Plumble crash when disconnection manually. (on 4.1.2)

### ISSUE THREAD

**Issue by BuddyButterfly** [Morlunk/Plumble#83]
When being on a server, tipping the back button brings up the disconnect dialog.
Confirming with yes, the app crashes. This is what I got out of the debugger. Does this make any sense?

For the exception the following info is given:

https://developer.android.com/reference/android/os/NetworkOnMainThreadException.html

Exception = {android.os.NetworkOnMainThreadException@830049841160}
cause =
{android.os.NetworkOnMainThreadException@830049841160}"android.os.NetworkOnMainThreadException"
detailMessage = null
stackState = {int[32]@830049800624}
stackTrace = null
suppressedExceptions = {java.util.ArrayList@830047807176} size = 0

<1> main@830034986248, prio=5, in group 'main', status: 'RUNNING'
      at
org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:903)
      at com.morlunk.jumble.net.JumbleTCP.disconnect(JumbleTCP.java:230)
      at
com.morlunk.jumble.net.JumbleConnection.disconnect(JumbleConnection.java:458)
      at com.morlunk.jumble.JumbleService.disconnect(JumbleService.java:345)
      at
com.morlunk.jumble.JumbleService$JumbleBinder.disconnect(JumbleService.java:521)
      at
com.morlunk.mumbleclient.app.PlumbleActivity$4.onClick(PlumbleActivity.java:302)
      at
com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loop(Looper.java:137)
      at android.app.ActivityThread.main(ActivityThread.java:4921)
      at java.lang.reflect.Method.invokeNative(Method.java:-1)
      at java.lang.reflect.Method.invoke(Method.java:511)
      at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
      at dalvik.system.NativeStart.main(NativeStart.java:-1)

**Comment by BuddyButterfly** [comment]
Here the log (nearly same):

D/InputReader( 2022): Input event: value=0
I/InputReader( 2022): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=38477058542000
I/InputDispatcher( 2022): Delivering touch to (10025): action: 0x1, toolType: 1
D/AndroidRuntime(10025): Shutting down VM
W/dalvikvm(10025): threadid=1: thread exiting with uncaught exception (group=0x41831da0)
E/AndroidRuntime(10025): FATAL EXCEPTION: main
E/AndroidRuntime(10025): Process: com.morlunk.mumbleclient, PID: 10025
E/AndroidRuntime(10025): android.os.NetworkOnMainThreadException
E/AndroidRuntime(10025):        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1166)
E/AndroidRuntime(10025):        at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1065)
E/AndroidRuntime(10025):        at com.morlunk.jumble.net.JumbleTCP.disconnect(JumbleTCP.java:230)
E/AndroidRuntime(10025):        at com.morlunk.jumble.net.JumbleConnection.disconnect(JumbleConnection.java:458)
E/AndroidRuntime(10025):        at com.morlunk.jumble.JumbleService.disconnect(JumbleService.java:345)
E/AndroidRuntime(10025):        at com.morlunk.jumble.JumbleService$JumbleBinder.disconnect(JumbleService.java:521)
E/AndroidRuntime(10025):        at com.morlunk.mumbleclient.app.PlumbleActivity$4.onClick(PlumbleActivity.java:302)
E/AndroidRuntime(10025):        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:170)
E/AndroidRuntime(10025):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10025):        at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(10025):        at android.app.ActivityThread.main(ActivityThread.java:5679)
E/AndroidRuntime(10025):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10025):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(10025):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
E/AndroidRuntime(10025):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
E/AndroidRuntime(10025):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 2022):   Force finishing activity com.morlunk.mumbleclient/.app.PlumbleActivity
D/CrashAnrDetector( 2022): processName: com.morlunk.mumbleclient
D/CrashAnrDetector( 2022): broadcastEvent : com.morlunk.mumbleclient data_app_crash
V/SmartFaceService - 3rd party pause( 2022): onReceive [android.intent.action.ACTIVITY_STATE/com.morlunk.mumbleclient/pause]

**Comment by BuddyButterfly** [comment]
I have looked into this issue a bit more deeply. The simple cause is that the android service has been used in a way it should be. An android service is intended to be run in background and do its work in background. To be able to run the intents in background, a thread must be created, that executes the messages received and thus does not do it on the main thread.

In Plumble an android service JumbleService is created. But, in contrary to the desired behaviour, all interactions done with the service are done on the main thread! Why is this? In Plumble there is an AsyncTask (thread) ServerConnectTask created, which is used to start the first service command. Though, the thread of AsyncTask does nothing special but only configuring the intent. The real action, starting the service, then is done in the postExecute method, which is executed on the main thread! All other actions are also done via triggers of user input and directly calling the interface of the service. Thus they are all run on the main thread. This is also the reason why tipping on the disconnect button directly calls through on the main thread to JumbleService.disconnect as can be seen in the stack trace above.

Background with code example of how to use an android service:
https://developer.android.com/guide/components/services.html#ExtendingService

Maybe it would be easier to use and IntentService if multithreading is not necessary:
https://developer.android.com/guide/components/services.html#ExtendingIntentService

**Comment by Morlunk** [comment]
The only issue here is that the TCP connection is being closed on the main thread. All network communication with jumble is delegated to worker threads normally, no need to worry :)

The AsyncTask that creates the service is only used because we need to make database calls.

IntentService is typically for one shot tasks, generally not desirable here.

Anyway, this is a pretty trivial fix that I'll finish up tonight. Sorry for the delay.

**Comment by BuddyButterfly** [comment]
No problem. OK, did not know the AsyncTask has been done because of database access. Is it that slow? I was guessing more than this is executed on the main thread. Now I saw that you are using a bound service. The audio of course is also threaded. Thanks for pointing me to that. If #83 is the only case where main thread calls through, than it is easy, indeed.

**Comment by BuddyButterfly** [comment]
Question. Shouldn't then all access via binding interface (that happens mostly on main thread) that accesses variables that are manipulated from other threads be synchronized? Though, I do not think there are so many variables of this type. I am not so deep in the code up till now...

**Comment by Morlunk** [comment]
Yes; this is only really an issue with IPC however. At the moment, as long as we make our calls from the main thread, there should be no issue. I would like to implement proper concurrency if/when PlumbleService becomes bindable out of process.

**Comment by BuddyButterfly** [comment]
Tested and confirmed! Works! Thanks a lot.
