### ISSUE TITLE
Screen always turned on

### ISSUE THREAD

**Issue by swistak35** [Morlunk/Plumble#94]
Hi,
In the beginning, thanks for providing such an app in Android community, it's one of my favourites.

Does any of you know, is there possible to add an option "leave screen always turned on"?

Root problem: I'm using push-to-talk. When I talk I use plumble on my tablet. However after some time of inactivity, the device's screen is dimming and turning off, so when I want to talk I have to turn on the tablet, unlock it and push the button - and it's quite inconvenient. What do you think?

**Comment by BuddyButterfly** [comment]
Hi,

this option is already available: "Stay awake" in the settings.

**Comment by swistak35** [comment]
Thanks! I didn't noticed that because I use version from the Google Play market.

**Comment by BuddyButterfly** [comment]
Welcome. Use Plumble nightly from [Plumble nightly] (https://www.morlunk.com/jenkins/job/Plumble-Nightly/). Their might be some issues with channel switching and users being displayed in the latest versions. Build #230 is ok.

**Comment by BuddyButterfly** [comment]
User/Channel issue has been fixed in version #233! Thanks, Morlunk!
